// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu8VsJLCrmYOMkGWtR58F2iPMYz_MAPgY',
    appId: '1:689596501135:web:dbf6fb678db4bddae474fa',
    messagingSenderId: '689596501135',
    projectId: 'ourapp-57275',
    authDomain: 'ourapp-57275.firebaseapp.com',
    storageBucket: 'ourapp-57275.firebasestorage.app',
    measurementId: 'G-KJ03VEML3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfdXnoiHEFIk0qtpNzA_VDwVMLW6h6WOs',
    appId: '1:689596501135:android:e36cf2ceeb70e8eee474fa',
    messagingSenderId: '689596501135',
    projectId: 'ourapp-57275',
    storageBucket: 'ourapp-57275.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvc8gGEH3ygca5UrKTFruGYnLphH7JsJQ',
    appId: '1:689596501135:ios:9ff1a8370ae124eae474fa',
    messagingSenderId: '689596501135',
    projectId: 'ourapp-57275',
    storageBucket: 'ourapp-57275.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvc8gGEH3ygca5UrKTFruGYnLphH7JsJQ',
    appId: '1:689596501135:ios:9ff1a8370ae124eae474fa',
    messagingSenderId: '689596501135',
    projectId: 'ourapp-57275',
    storageBucket: 'ourapp-57275.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCu8VsJLCrmYOMkGWtR58F2iPMYz_MAPgY',
    appId: '1:689596501135:web:cf8fa685d1e5fe5ce474fa',
    messagingSenderId: '689596501135',
    projectId: 'ourapp-57275',
    authDomain: 'ourapp-57275.firebaseapp.com',
    storageBucket: 'ourapp-57275.firebasestorage.app',
    measurementId: 'G-DN6303ZZ1Q',
  );
}
